# Generated by Django 3.0.10 on 2021-04-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specrun',
            options={'permissions': [('can_upload', 'Can upload a CD spec model'), ('can_edit', 'Can edit a CD spec model'), ('can_delete', 'Can delete a CD spec model')]},
        ),
    ]
