# Generated by Django 3.0.10 on 2021-04-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0005_specrun_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='specrun',
            name='upload_user_string',
            field=models.CharField(default='', max_length=150),
        ),
    ]
