# Generated by Django 3.1.7 on 2021-03-17 02:44

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('run_date', models.DateTimeField(verbose_name='Run Date')),
                ('run_user', models.CharField(max_length=64, verbose_name='Run by:')),
                ('run_title', models.CharField(max_length=64, verbose_name='Title')),
                ('run_description', models.TextField(max_length=2000, verbose_name='Description (Character Limit: 2000)')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Raw Data')),
                ('data_points', models.IntegerField(verbose_name='Data Points')),
                ('visible_student', models.BooleanField(default=False, verbose_name='Visible to Students')),
                ('visible_public', models.BooleanField(default=False, verbose_name='Visible to Public')),
                ('source_file', models.FileField(upload_to='cdspecruns', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('protein_concentration', models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Protein Concentration')),
                ('pathlength', models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Curvette Pathlength')),
                ('number_of_amino_acids', models.IntegerField(verbose_name='Number of amino acids')),
                ('x_units', models.CharField(max_length=64, null=True, verbose_name='XUNITS')),
                ('y_units', models.CharField(max_length=64, null=True, verbose_name='YUNITS')),
                ('y2_units', models.CharField(max_length=64, null=True, verbose_name='Y2UNITS')),
                ('y3_units', models.CharField(max_length=64, null=True, verbose_name='Y3UNITS')),
            ],
        ),
    ]
