# Generated by Django 3.0.10 on 2020-11-01 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('run_date', models.DateTimeField(verbose_name='Run Date')),
                ('run_title', models.CharField(max_length=64, verbose_name='Title')),
                ('run_description', models.TextField(verbose_name='Description')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Raw Data')),
                ('data_points', models.IntegerField(verbose_name='Data Points')),
                ('visible_student', models.BooleanField(default=False, verbose_name='Visible to Students')),
                ('visible_public', models.BooleanField(default=False, verbose_name='Visible to Public')),
                ('source_file', models.FileField(upload_to='cdspecruns')),
            ],
        ),
    ]
