# Generated by Django 3.0.10 on 2020-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specrun',
            name='number_of_amino_acids',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10, verbose_name='Number of amino acids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specrun',
            name='pathlength',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10, verbose_name='Curvette Pathlength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specrun',
            name='protein_concentration',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10, verbose_name='Protein Concentration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specrun',
            name='run_user',
            field=models.CharField(default=10, max_length=64, verbose_name='Run by:'),
            preserve_default=False,
        ),
    ]
