# Generated by Django 3.0.10 on 2020-11-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0002_auto_20201101_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='specrun',
            name='absorbance_index',
            field=models.IntegerField(null=True, verbose_name='Absorbance Index'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='degrees_index',
            field=models.IntegerField(null=True, verbose_name='Degrees Index'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='voltage_index',
            field=models.IntegerField(null=True, verbose_name='Voltage Index'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='x_index',
            field=models.IntegerField(null=True, verbose_name='X Index'),
        ),
    ]
