# Generated by Django 3.0.10 on 2021-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0004_auto_20210219_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specrun',
            name='absorbance_index',
        ),
        migrations.RemoveField(
            model_name='specrun',
            name='degrees_index',
        ),
        migrations.RemoveField(
            model_name='specrun',
            name='voltage_index',
        ),
        migrations.RemoveField(
            model_name='specrun',
            name='x_index',
        ),
        migrations.AddField(
            model_name='specrun',
            name='x_units',
            field=models.CharField(max_length=64, null=True, verbose_name='XUNITS'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='y2_units',
            field=models.CharField(max_length=64, null=True, verbose_name='Y2UNITS'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='y3_units',
            field=models.CharField(max_length=64, null=True, verbose_name='Y3UNITS'),
        ),
        migrations.AddField(
            model_name='specrun',
            name='y_units',
            field=models.CharField(max_length=64, null=True, verbose_name='YUNITS'),
        ),
        migrations.AlterField(
            model_name='specrun',
            name='run_description',
            field=models.TextField(max_length=2000, verbose_name='Description (Character Limit: 2000)'),
        ),
    ]
