# Generated by Django 3.0.10 on 2021-02-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0005_auto_20210222_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specrun',
            name='number_of_amino_acids',
            field=models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Number of amino acids'),
        ),
        migrations.AlterField(
            model_name='specrun',
            name='pathlength',
            field=models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Curvette Pathlength'),
        ),
        migrations.AlterField(
            model_name='specrun',
            name='protein_concentration',
            field=models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Protein Concentration'),
        ),
    ]
