# Generated by Django 3.0.10 on 2021-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0007_auto_20210222_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specrun',
            name='pathlength',
            field=models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Curvette Pathlength'),
        ),
    ]
