# Generated by Django 3.0.10 on 2021-04-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0002_auto_20210420_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specrun',
            options={},
        ),
    ]
