# Generated by Django 3.0.10 on 2021-04-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdspec', '0003_auto_20210420_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specrun',
            options={'permissions': [('can_upload', 'Can upload a CD spec model'), ('can_edit', 'Can edit a CD spec model'), ('can_delete', 'Can delete a CD spec model'), ('can_view_student', 'Can view a CD spec model for students'), ('can_view_all', 'Can view any CD spec model')]},
        ),
    ]
