# Generated by Django 3.0.10 on 2021-04-22 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdspec', '0004_auto_20210421_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='specrun',
            name='upload_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
